/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hifiremote_decodeir_DecodeIRCaller */

#ifndef _Included_com_hifiremote_decodeir_DecodeIRCaller
#define _Included_com_hifiremote_decodeir_DecodeIRCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hifiremote_decodeir_DecodeIRCaller
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hifiremote_decodeir_DecodeIRCaller_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_hifiremote_decodeir_DecodeIRCaller
 * Method:    decode
 * Signature: ([I[III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hifiremote_decodeir_DecodeIRCaller_decode
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_hifiremote_decodeir_DecodeIRCaller
 * Method:    decode2
 * Signature: ([I[IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hifiremote_decodeir_DecodeIRCaller_decode2
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
